from __future__ import annotations

import importlib
import json
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_ROOT = PROJECT_ROOT / "system_skills" / "discover-data-relations" / "scripts"
sys.path.insert(0, str(SCRIPT_ROOT))


PROGRESSIVE = importlib.import_module("progressive_engine")
SCENARIO = importlib.import_module("scenario_engine")


class OperationalContractTests(unittest.TestCase):
    def test_external_capability_cannot_claim_a_local_result_file(self) -> None:
        cards = [
            {
                "id": "E-input",
                "kind": "file_structure",
                "strength": "structural",
                "sources": [{"file": "input.csv", "locator": "file"}],
            },
            {
                "id": "E-result",
                "kind": "file_structure",
                "strength": "structural",
                "sources": [{"file": "result.xlsx", "locator": "file"}],
            },
            {
                "id": "E-relation",
                "kind": "goal_relation_statement",
                "strength": "direct",
                "sources": [{"file": "description.md", "locator": "line:1"}],
            },
        ]
        claims = {
            "nodes": [
                {"id": "n_input", "name": "Business input", "type": "input", "evidence_ids": ["E-input"]},
                {"id": "n_decision", "name": "Business decision", "type": "decision", "evidence_ids": ["E-relation"]},
                {
                    "id": "n_external",
                    "name": "External knowledge crawler",
                    "type": "object",
                    "description": "Remote API enrichment",
                    "evidence_ids": ["E-result"],
                },
                {"id": "n_output", "name": "Business output", "type": "output", "evidence_ids": ["E-result"]},
            ],
            "edges": [
                {
                    "id": "e-input",
                    "source": "n_input",
                    "target": "n_decision",
                    "type": "feeds",
                    "confidence": 0.9,
                    "evidence_ids": ["E-relation"],
                },
                {
                    "id": "e-external",
                    "source": "n_external",
                    "target": "n_decision",
                    "type": "feeds",
                    "confidence": 0.9,
                    "evidence_ids": ["E-relation"],
                },
                {
                    "id": "e-output",
                    "source": "n_decision",
                    "target": "n_output",
                    "type": "derives",
                    "confidence": 0.9,
                    "evidence_ids": ["E-relation"],
                },
            ],
            "main_chain": ["n_input", "n_decision", "n_output"],
            "branches": [],
            "coverage": {"included_files": ["input.csv", "result.xlsx"], "excluded_files": []},
        }
        errors = SCENARIO.validate_claims(
            claims, {"cards": cards, "coverage": {"files": ["input.csv", "result.xlsx"]}}
        )
        self.assertTrue(any("must use type system" in item for item in errors))
        self.assertTrue(any("must not assign local data files" in item for item in errors))

    def test_header_detection_skips_title_and_note_rows(self) -> None:
        rows = [
            ["国家医疗保障基金违规问题清单", None, None, None],
            ["说明：以下字段共同构成完整规则", None, None, None],
            ["序号", "问题清单", "违规类型", "国家违规参考示例"],
            [1, "重复收费", "虚构项目", "示例内容"],
        ]
        row, confidence = PROGRESSIVE.detect_header_row(rows)
        self.assertEqual(row, 2)
        self.assertGreaterEqual(confidence, 0.5)

    def test_header_detection_does_not_require_domain_specific_names(self) -> None:
        rows = [
            ["Quarterly export", None, None],
            ["Generated by another system", None, None],
            ["Alpha", "Beta", "Gamma"],
            [1001, "north", 19.5],
            [1002, "south", 21.0],
        ]
        row, confidence = PROGRESSIVE.detect_header_row(rows)
        self.assertEqual(row, 2)
        self.assertGreaterEqual(confidence, 0.5)

    def test_csv_inspection_uses_detected_business_header(self) -> None:
        with TemporaryDirectory() as temporary:
            path = Path(temporary) / "规则表.csv"
            path.write_text(
                "国家医疗保障基金违规问题清单,,,\n"
                "说明：以下字段共同构成完整规则,,,\n"
                "序号,问题清单,违规类型,用途\n"
                "1,重复收费,虚构项目,审计\n",
                encoding="utf-8",
            )
            table = PROGRESSIVE.inspect_csv(1, "规则表.csv", path)[0]
            self.assertEqual(table.header_row, 2)
            self.assertEqual([item.name for item in table.columns], ["序号", "问题清单", "违规类型", "用途"])

    def test_xlsx_row_probe_uses_detected_header_and_selected_columns(self) -> None:
        with TemporaryDirectory() as temporary:
            from openpyxl import Workbook

            path = Path(temporary) / "规则表.xlsx"
            workbook = Workbook()
            sheet = workbook.active
            sheet.title = "规则"
            sheet.append(["国家医疗保障基金违规问题清单", None, None])
            sheet.append(["说明：以下字段共同构成完整规则", None, None])
            sheet.append(["序号", "问题清单", "用途"])
            sheet.append([1, "重复收费", "审计"])
            sheet.append([2, "超标准收费", "现场检查"])
            workbook.save(path)
            workbook.close()

            table = PROGRESSIVE.inspect_xlsx(1, "规则表.xlsx", path)[0]
            self.assertEqual(table.header_row, 2)
            rows = list(PROGRESSIVE.iter_table_rows(table, path, table.columns[:2]))
            limited = list(
                PROGRESSIVE.iter_table_rows(table, path, table.columns[:2], row_limit=1)
            )
            self.assertEqual(limited, rows[:1])
            self.assertEqual(rows[0], (4, {"序号": "1", "问题清单": "重复收费"}))
            self.assertEqual(rows[1], (5, {"序号": "2", "问题清单": "超标准收费"}))

    def test_large_xlsx_probe_materializes_only_seed_matches(self) -> None:
        if PROGRESSIVE._fastexcel() is None:
            self.skipTest("fastexcel is not installed in this test environment")
        with TemporaryDirectory() as temporary:
            from openpyxl import Workbook

            root = Path(temporary)
            input_root = root / "input"
            output_root = root / "output"
            input_root.mkdir()

            seed_path = input_root / "result.xlsx"
            workbook = Workbook()
            sheet = workbook.active
            sheet.append(["record_id", "display_name"])
            sheet.append(["A00001", "one"])
            sheet.append(["A00199", "last"])
            workbook.save(seed_path)
            workbook.close()

            large_path = input_root / "events.xlsx"
            workbook = Workbook()
            sheet = workbook.active
            sheet.append(["Export title", None])
            sheet.append(["Generated automatically", None])
            sheet.append(["record_id", "display_name"])
            for index in range(1, 201):
                sheet.append([f"A{index:05d}", f"name-{index}"])
            workbook.save(large_path)
            workbook.close()

            args = PROGRESSIVE.build_parser().parse_args([
                "analyze",
                "--input", str(input_root),
                "--output", str(output_root),
                "--goal-file", "",
                "--deadline-seconds", "60",
                "--seed-cell-budget", "20",
                "--profile-sample-rows", "16",
            ])
            result = PROGRESSIVE.ProgressiveAnalyzer(input_root, output_root, args).run()

            event_scan = next(
                value for value in result["scan_stats"].values()
                if value.get("mode") == "arrow_directed_probe"
            )
            self.assertEqual(result["status"], "complete")
            self.assertEqual(event_scan["rows_scanned"], 200)
            self.assertLessEqual(event_scan["rows_materialized"], 2)
            self.assertTrue(result["relations"])

    def test_contract_combines_field_joins_and_document_retrieval_routes(self) -> None:
        with TemporaryDirectory() as temporary:
            root = Path(temporary)
            field_path = root / "relations.json"
            field_result = {
                "status": "complete",
                "files": [
                    {
                        "path": "claims.csv", "extension": ".csv", "kind": "tabular", "size": 1000,
                        "tables": [{
                            "key": "claims", "table_name": "claims.csv", "row_count": 100000,
                            "columns": [
                                {"name": "业务ID", "query_name": "业务ID", "kind": "id"},
                                {"name": "金额", "query_name": "金额", "kind": "other"},
                            ],
                            "header_row": 0, "header_confidence": 1.0, "header_detection": "first_row",
                        }],
                    },
                    {
                        "path": "results.csv", "extension": ".csv", "kind": "tabular", "size": 100,
                        "tables": [{
                            "key": "results", "table_name": "results.csv", "row_count": 10,
                            "columns": [
                                {"name": "业务ID", "query_name": "业务ID", "kind": "id"},
                                {"name": "结论", "query_name": "结论", "kind": "other"},
                            ],
                            "header_row": 0, "header_confidence": 1.0, "header_detection": "first_row",
                        }],
                    },
                    {"path": "policy.pdf", "extension": ".pdf", "kind": "document", "size": 500, "tables": []},
                ],
                "column_statistics": [
                    {"file": "claims.csv", "column": "业务ID", "nonempty": 1000, "distinct_ratio": 1.0},
                    {"file": "results.csv", "column": "业务ID", "nonempty": 10, "distinct_ratio": 1.0},
                ],
            }
            field_path.write_text(json.dumps(field_result, ensure_ascii=False), encoding="utf-8")
            cards = [
                {"id": "E-A", "kind": "file_structure", "sources": [{"file": "claims.csv", "locator": "file"}]},
                {"id": "E-R", "kind": "file_structure", "sources": [{"file": "results.csv", "locator": "file"}]},
                {"id": "E-P", "kind": "document_relation_statement", "sources": [{"file": "policy.pdf", "locator": "page:2"}]},
                {
                    "id": "E-L", "kind": "field_relationship",
                    "sources": [
                        {"file": "claims.csv", "locator": "column:业务ID"},
                        {"file": "results.csv", "locator": "column:业务ID"},
                    ],
                    "facts": {
                        "source_file": "claims.csv", "target_file": "results.csv",
                        "correspondences": [{
                            "source_field": "业务ID", "target_field": "业务ID",
                            "alignment": "same_header", "confidence": 0.99, "evidence_count": 10,
                        }],
                    },
                },
            ]
            cards_by_id = {item["id"]: item for item in cards}
            claims = {
                "scenario": {"name": "审计", "purpose": "发现违规"},
                "nodes": [
                    {"id": "n_input", "name": "业务数据", "type": "input", "evidence_ids": ["E-A"]},
                    {"id": "n_rule", "name": "规则材料", "type": "rule", "evidence_ids": ["E-P"]},
                    {"id": "n_decision", "name": "审计判断", "type": "decision", "evidence_ids": ["E-A"]},
                    {"id": "n_result", "name": "审计结果", "type": "output", "evidence_ids": ["E-R"]},
                ],
                "edges": [
                    {"id": "e-govern", "source": "n_rule", "target": "n_decision", "type": "governs", "evidence_ids": ["E-P"]},
                    {"id": "e-trace", "source": "n_input", "target": "n_result", "type": "joins_with", "evidence_ids": ["E-L"]},
                ],
            }
            contract = SCENARIO.build_operational_contract(
                claims, {"cards": cards}, cards_by_id, field_result, field_path
            )
            self.assertEqual(contract["status"], "ready", contract["quality_gates"])
            self.assertTrue(contract["links"][0]["recommended_candidate"])
            self.assertFalse(contract["links"][0]["runtime_eligible"])
            self.assertEqual(len(contract["semantic_routes"]), 1)
            claims_source = next(item for item in contract["sources"] if item["path"] == "claims.csv")
            result_source = next(item for item in contract["sources"] if item["path"] == "results.csv")
            policy = next(item for item in contract["sources"] if item["path"] == "policy.pdf")
            self.assertEqual(claims_source["lifecycle"], "runtime_input")
            self.assertTrue(claims_source["runtime_required"])
            self.assertEqual(result_source["lifecycle"], "design_time_template")
            self.assertFalse(result_source["runtime_required"])
            self.assertEqual(contract["template_source_ids"], [result_source["source_id"]])
            self.assertNotIn(result_source["source_id"], contract["runtime_source_ids"])
            self.assertEqual(policy["content_retrieval"]["mode"], "parse_then_chunk_index")
            self.assertEqual(policy["content_retrieval"]["ocr_policy"], "fallback_when_text_layer_is_sparse")
            self.assertEqual(policy["lifecycle"], "runtime_input")
            self.assertTrue(all(item["agent_must_not_open_directly"] for item in contract["sources"]))

            cards_without_field_link = [item for item in cards if item["id"] != "E-L"]
            claims_without_field_link = json.loads(json.dumps(claims, ensure_ascii=False))
            claims_without_field_link["edges"] = [claims_without_field_link["edges"][0]]
            blocked = SCENARIO.build_operational_contract(
                claims_without_field_link,
                {"cards": cards_without_field_link},
                {item["id"]: item for item in cards_without_field_link},
                field_result,
                field_path,
            )
            self.assertTrue(blocked["semantic_routes"])
            self.assertEqual(blocked["status"], "blocked")
            self.assertTrue(any("结构化结果样例" in item for item in blocked["quality_gates"]["blockers"]))


if __name__ == "__main__":
    unittest.main()
