import type { Language } from '@/types/studio'

export const studioCopy: Record<Language, Record<string, string>> = {
  zh: {
    activityBar: '主导航',
    activeFile: '当前文件',
    activeModel: '当前模型',
    activeScene: '当前场景',
    add: '添加',
    aiAssistant: 'AI 助手',
    aiModels: 'AI 模型',
    aiUnderstanding: 'AI 理解',
    businessContext: '业务上下文',
    businessExplorer: '业务资源管理器',
    businessWorkspace: '业务工作区',
    cancel: '取消',
    chatEmptyBody: '描述业务目标、补充规则或让 AI 分析当前场景。',
    chatEmptyTitle: '从一个业务问题开始',
    chatPlaceholder: '输入业务问题或补充说明...',
    chatActions: '会话操作',
    chatSessions: '对话会话',
    clearChat: '清空当前会话',
    clearChatConfirm: '只清空当前会话的消息和执行记录，业务上下文与文件不会被删除。',
    close: '关闭',
    configuredModels: '已配置模型',
    confirm: '确认',
    confirmQuestion: '确认问题',
    confirmations: '确认记录',
    copied: '已复制',
    copyExample: '复制示例',
    copyReply: '复制回复',
    create: '创建',
    download: '下载',
    deleteChat: '删除当前会话',
    deleteChatConfirm: '删除当前会话及其消息和执行记录，业务上下文与文件不受影响。',
    entities: '实体',
    evidence: '证据',
    explorer: '资源管理器',
    files: '文件',
    general: '通用',
    generating: '生成中',
    goal: '目标',
    goalPlaceholder: '生成可复用的业务 Skill Package',
    language: '语言',
    languageHelp: '切换工作台界面语言，适合不同用户使用。',
    latestPlan: '最新计划',
    latestMessage: '回到最新消息',
    mcpConfigInvalid: 'MCP 配置不是有效 JSON',
    mcpConfigSaved: 'MCP 配置已保存',
    model: '模型',
    modelId: '模型 ID',
    modelName: '名称',
    modelsHelp: '这里管理可选 AI 模型；对话区只显示已启用模型。',
    modified: '已修改',
    name: '名称',
    newBusinessScene: '新建业务场景',
    newChat: '新建会话',
    newScene: '新建场景',
    noAssumptions: '暂无假设。',
    noConfirmations: '暂无确认记录。',
    noModel: '未配置模型',
    noPackage: '最终业务能力包尚未生成。',
    noPreview: '暂无预览文本。',
    noRun: '暂无运行记录。',
    openQuestions: '待确认问题',
    openSettings: '打开设置',
    packages: '生成包',
    plan: '计划',
    questions: '问题',
    refresh: '刷新',
    refreshWorkspace: '刷新工作区',
    resizeAssistant: '调整 AI 对话栏宽度',
    resizeExplorer: '调整资源管理器宽度',
    ready: '就绪',
    relations: '关系',
    reload: '重新加载',
    saveAndAnalyze: '保存并分析',
    saveConfig: '保存配置',
    saved: '已保存',
    scenarioDescription: '场景描述',
    scenarioSaved: 'description.md 已保存',
    sceneNamePlaceholder: '例如：电商客服 Agent',
    send: '发送',
    sendHint: 'Ctrl + Enter 发送',
    settings: '设置',
    settingsDescription: '像编辑器一样集中管理模型、工具、Skill、MCP、语言和主题。',
    skills: '技能',
    statusAnalyzed: '已分析',
    statusConfirmed: '已确认',
    statusCreated: '已创建',
    statusFilesUploaded: '已上传文件',
    statusOutputsGenerated: '已生成输出',
    stop: '停止生成',
    theme: '主题',
    themeContrast: '高对比',
    themeDark: '深色',
    themeHelp: '切换整体工作台视觉主题。',
    themeLight: '浅色',
    tools: '工具',
    uploadData: '上传资料',
    uploadSuccess: '资料已上传到 data',
    version: '版本',
    workspace: '工作区',
    workspaceFallback: '业务工作区',
    writeContext: '写入 Context',
    you: '你',
  },
  en: {
    activityBar: 'Activity Bar',
    activeFile: 'Active File',
    activeModel: 'Active Model',
    activeScene: 'Active Scene',
    add: 'Add',
    aiAssistant: 'AI Assistant',
    aiModels: 'AI Models',
    aiUnderstanding: 'AI Understanding',
    businessContext: 'Business Context',
    businessExplorer: 'Business Explorer',
    businessWorkspace: 'Business Workspace',
    cancel: 'Cancel',
    chatEmptyBody: 'Describe a goal, add rules, or ask AI to analyze this workspace.',
    chatEmptyTitle: 'Start with a business question',
    chatPlaceholder: 'Ask a business question or add context...',
    chatActions: 'Chat actions',
    chatSessions: 'Chat sessions',
    clearChat: 'Clear current chat',
    clearChatConfirm: 'This only clears messages and runs in the current chat. Business context and files are kept.',
    close: 'Close',
    configuredModels: 'Configured Models',
    confirm: 'Confirm',
    confirmQuestion: 'Confirm Question',
    confirmations: 'Confirmations',
    copied: 'Copied',
    copyExample: 'Copy Example',
    copyReply: 'Copy response',
    create: 'Create',
    download: 'Download',
    deleteChat: 'Delete current chat',
    deleteChatConfirm: 'This deletes the current chat and its runs. Business context and files are kept.',
    entities: 'Entities',
    evidence: 'Evidence',
    explorer: 'Explorer',
    files: 'files',
    general: 'General',
    generating: 'Generating',
    goal: 'Goal',
    goalPlaceholder: 'Generate a reusable business Skill Package',
    language: 'Language',
    languageHelp: 'Switch the workbench language for different users.',
    latestPlan: 'Latest Plan',
    latestMessage: 'Jump to latest message',
    mcpConfigInvalid: 'MCP config is not valid JSON',
    mcpConfigSaved: 'MCP config saved',
    model: 'Model',
    modelId: 'Model ID',
    modelName: 'Name',
    modelsHelp: 'Manage selectable AI models here. The chat only shows enabled models.',
    modified: 'modified',
    name: 'Name',
    newBusinessScene: 'New Business Scene',
    newChat: 'New Chat',
    newScene: 'New Scene',
    noAssumptions: 'No assumptions yet.',
    noConfirmations: 'No confirmations yet.',
    noModel: 'No model',
    noPackage: 'The final business capability package has not been generated.',
    noPreview: 'No preview text.',
    noRun: 'No run yet.',
    openQuestions: 'Open Questions',
    openSettings: 'Open Settings',
    packages: 'packages',
    plan: 'Plan',
    questions: 'questions',
    refresh: 'Refresh',
    refreshWorkspace: 'Refresh Workspace',
    resizeAssistant: 'Resize AI chat panel',
    resizeExplorer: 'Resize explorer panel',
    ready: 'Ready',
    relations: 'Relations',
    reload: 'Reload',
    saveAndAnalyze: 'Save and Analyze',
    saveConfig: 'Save Config',
    saved: 'saved',
    scenarioDescription: 'Scenario Description',
    scenarioSaved: 'description.md saved',
    sceneNamePlaceholder: 'For example: Ecommerce Support Agent',
    send: 'Send',
    sendHint: 'Ctrl + Enter to send',
    settings: 'Settings',
    settingsDescription: 'Manage models, tools, skills, MCP, language, and theme in one editor-style place.',
    skills: 'Skills',
    statusAnalyzed: 'analyzed',
    statusConfirmed: 'confirmed',
    statusCreated: 'created',
    statusFilesUploaded: 'files uploaded',
    statusOutputsGenerated: 'outputs generated',
    stop: 'Stop generating',
    theme: 'Theme',
    themeContrast: 'High Contrast',
    themeDark: 'Dark',
    themeHelp: 'Switch the entire workbench visual theme.',
    themeLight: 'Light',
    tools: 'Tools',
    uploadData: 'Upload Data',
    uploadSuccess: 'Uploaded to data',
    version: 'Version',
    workspace: 'Workspace',
    workspaceFallback: 'Business Workspace',
    writeContext: 'Write to Context',
    you: 'You',
  },
}

Object.assign(studioCopy.zh, {
  chatPlaceholder: '输入业务问题，使用 @ 引用场景文件...',
  deleteFile: '删除文件',
  deleteFileConfirmBody: '文件将从当前业务场景永久删除。依赖它的分析结果需要重新运行后才能继续信任。',
  deleteFileConfirmTitle: '删除这个文件？',
  deleteScene: '删除场景',
  deleteSceneConfirmBody: '这会永久删除该业务场景的说明、上下文、资料文件和全部业务产物。',
  deleteSceneConfirmTitle: '删除业务场景？',
  deleted: '已删除',
  filePreviewLimited: '表格预览仅显示前 20 行，避免大数据文件卡顿。',
  filePreviewLoading: '加载中',
  filePreviewTruncated: '有界预览',
  mentionFile: '引用场景文件',
  mentionFileEmpty: '没有找到匹配的文件',
  mentionFileHint: '↑↓ 选择 · Enter 确认 · Esc 关闭',
  mentionFileRemove: '移除文件引用',
  mentionFileResults: '个匹配文件',
  needUserInput: '需要你确认',
  referencedFilesPrompt: '引用的业务场景文件：',
  resumeFailed: 'AI 续跑未完成，可从暂停点继续。',
  retryContinue: '继续执行',
  fileOperationCreate: '正在创建',
  fileOperationEdit: '正在编辑',
  fileOperationMove: '正在移动',
  fileOperationDelete: '正在删除',
  fileOperationManage: '正在更新',
  newFile: '新建文件',
  newFolder: '新建文件夹',
  rename: '重命名',
  renamed: '已重命名',
  resourceName: '名称',
  invalidResourceName: '名称不能为空，且不能包含 \\ / : * ? " < > |',
  fileCreated: '文件已创建',
  folderCreated: '文件夹已创建',
  filesImported: '个文件已导入',
  deleteFolderConfirm: '这会删除文件夹以及其中的全部内容。',
  workspaceOperationFailed: '工作区操作失败',
})

Object.assign(studioCopy.en, {
  chatPlaceholder: 'Ask a business question, or use @ to reference a scene file...',
  deleteFile: 'Delete File',
  deleteFileConfirmBody: 'This permanently removes the file from the business scene. Re-run any analysis that depends on it.',
  deleteFileConfirmTitle: 'Delete this file?',
  deleteScene: 'Delete Scene',
  deleteSceneConfirmBody: 'This permanently deletes the scene description, context, source files, and all business outputs.',
  deleteSceneConfirmTitle: 'Delete business scene?',
  deleted: 'Deleted',
  filePreviewLimited: 'Table previews show the first 20 rows only to keep large files responsive.',
  filePreviewLoading: 'Loading',
  filePreviewTruncated: 'Bounded preview',
  mentionFile: 'Reference scene file',
  mentionFileEmpty: 'No matching files',
  mentionFileHint: '↑↓ Select · Enter Confirm · Esc Close',
  mentionFileRemove: 'Remove file reference',
  mentionFileResults: 'matching files',
  needUserInput: 'Input Needed',
  referencedFilesPrompt: 'Referenced business scene files:',
  resumeFailed: 'AI continuation did not finish. Continue from the paused step.',
  retryContinue: 'Continue',
  fileOperationCreate: 'Creating',
  fileOperationEdit: 'Editing',
  fileOperationMove: 'Moving',
  fileOperationDelete: 'Deleting',
  fileOperationManage: 'Updating',
  newFile: 'New File',
  newFolder: 'New Folder',
  rename: 'Rename',
  renamed: 'Renamed',
  resourceName: 'Name',
  invalidResourceName: 'Names cannot be empty or contain \\ / : * ? " < > |',
  fileCreated: 'File created',
  folderCreated: 'Folder created',
  filesImported: 'files imported',
  deleteFolderConfirm: 'This deletes the folder and everything inside it.',
  workspaceOperationFailed: 'Workspace operation failed',
})
